### ISSUE TITLE
How do I make shops?

### ISSUE THREAD

**Issue by LandonAndEmma** [fuji-fabric/fuji#138]
EssentialsX has stuff where you can make player shops but I can't find any of that in the fuji manual, so it it not added or what?

**Comment by sakurawald** [comment]
Hello, to support players to host player shops, i would recommend you to use the https://modrinth.com/mod/universal-shops mod, which plays a role like `quickshop` in bukkit.

The situation in fabric platform is a bit different. There is not a universal economy system in fabric like `vault` in bukkit, and the economy system in fabric is also poor, so it's better to use a `item based shop` instead of a `currency based shop`.

Also, for the same reason, fuji also doesn't provides some commands like `/balance`, `/worth` and `/balancetop` which requires a universal currency system.

**Comment by sakurawald** [comment]
Here is another shop mod that may fit your need: https://modrinth.com/mod/servershop
Still there should be a universal economy system in fabric.

**Comment by sakurawald** [comment]
In `v10.1.0` version, we now have the integration with `common economy api`.
You can enable the `economy` module, and define your own currencies type.
Install the `Universal Shops` mod, and you get the `QuickShop` gameplay in fabric server.
