### ISSUE TITLE
How to assign rights and prefixes of rights

### ISSUE THREAD

**Issue by Itsporo** [fuji-fabric/fuji#20]
I'm using luckperms to assign permissions, but when I turn off CommandPermissionModule, I can't assign permissions in the fuji.<command> style for each command. Enabling this module adds a prefix to all other commands. Is there any way to fix this?

**Comment by sakurawald** [comment]
Enable `command permission module` should not conflict with luckperms.

For example, the `/seed` command provided by mojang requires no permission (`/seed` requires the player to be op).
If you add a permission `fuji.seed` for the group `default`, thne it means `/seed` command now required the permission `fuji.seed` for the players inside group `default` to use.

**Or in other words. `command permission module` is used to `override` the `requirement of command node`.** You can issue `/lp user <player> permission set fuji.seed true` for a player, so that he can use the command `/seed`.
And issue `/lp user <player> permission set fuji.seed false` so that the player can't use `/seed` command.
Or you just unset the `override` by issuing `/lp user <player> permission unset fuji.seed`, then everything is back to the normal.

The command `/seed` provided by mojang is only available for `op` player. Let's say you want to let some normal player use `/seed` command, but you don't want to grant op for them. Then you can issue `/lp group default permission set fuji.seed true` for them.

**Comment by Itsporo** [comment]
ok, thanks

> Enable `command permission module` should not conflict with luckperms.
> 
> For example, the `/seed` command provided by mojang requires no permission (`/seed` requires the player to be op). If you add a permission `fuji.seed` for the group `default`, thne it means `/seed` command now required the permission `fuji.seed` for the players inside group `default` to use.
> 
> **Or in other words. `command permission module` is used to `override` the `requirement of command node`.** You can issue `/lp user <player> permission set fuji.seed true` for a player, so that he can use the command `/seed`. And issue `/lp user <player> permission set fuji.seed false` so that the player can't use `/seed` command. Or you just unset the `override` by issuing `/lp user <player> permission unset fuji.seed`, then everything is back to the normal.
> 
> The command `/seed` provided by mojang is only available for `op` player. Let's say you want to let some normal player use `/seed` command, but you don't want to grant op for them. Then you can issue `/lp group default permission set fuji.seed true` for them.
