### ISSUE TITLE
Fuji's new 1.2.4-partial-backport crashes minecraft on launch

### ISSUE THREAD

**Issue by Tanjiraaaaa** [fuji-fabric/fuji#23]
I have confirmed that it is because of Fuji
Here are the logs of the [crash](https://pastes.dev/5hO0rYf7FV)
Also I just wanted to say, this is one of the best mods that adds commands to fabric I've seen :DD
And it is very underrated, Keep up the good work !

**Comment by sakurawald** [comment]
Duped, https://github.com/sakurawald/fuji-fabric/issues/22

The 1.2.4-partial-backport reverts some codes in the latest version, and i forget to register these events. We are plan to add more tests before each publish to avoid similar accidents.

**Comment by sakurawald** [comment]
This is because the latest version changed the module `BetterFakePlaer` into `FakePlayerManager`.
If the configuration key is missing, then it will force enable this module.
And you need to install `carpet` mod before you enable `BetterFakePlayer`/`FakePlayerManager` module.

As you can see in
```
[20:41:23] [main/ERROR]: The enable-supplier key 'modules.better_fake_player.enable' is missing -> force enable this module
[20:41:23] [main/ERROR]: The enable-supplier key 'modules.better_fake_player.enable' is missing -> force enable this module
[20:41:23] [main/ERROR]: The enable-supplier key 'modules.better_fake_player.enable' is missing -> force enable this module
[20:41:23] [main/ERROR]: The enable-supplier key 'modules.stronger_player_list.enable' is missing -> force enable this module
[20:41:23] [main/ERROR]: The enable-supplier key 'modules.stronger_player_list.enable' is missing -> force enable this module
[20:41:23] [main/ERROR]: The enable-supplier key 'modules.tick_chunk_cache.enable' is missing -> force enable this module
[20:41:23] [main/ERROR]: The enable-supplier key 'modules.tick_chunk_cache.enable' is missing -> force enable this module
[20:41:23] [main/ERROR]: The enable-supplier key 'modules.whitelist_fix.enable' is missing -> force enable this module
[20:41:23] [main/ERROR]: The enable-supplier key 'modules.zero_command_permission.enable' is missing -> force enable this module
```

The simplest work around is to install `fuji` in a test environment to let fuji generates the default `config.json`, and you can see the difference between these versions.

**Comment by Tanjiraaaaa** [comment]
I've installed carpet mod and ran fuji without any other mods except for the dependencies but it still crashed with the same [logs](https://pastes.dev/BLk39JQDmQ)

**Comment by Tanjiraaaaa** [comment]
I'm sorry but idk how to do this myself 🙏

**Comment by sakurawald** [comment]
> I'm sorry but idk how to do this myself 🙏

For example, if you see this message in your logs
```
[20:41:23] [main/ERROR]: The enable-supplier key 'modules.better_fake_player.enable' is missing -> force enable this module
```
Then it means fuji can't find the configuration key `modules.better_fake_player.enable` in `config.json`
To solve this, you have 2 methods.
**The first method**: you can use a text editor to open `config.json` and you manually add the configuration key `modules.better_fake_player.enable` and set it to `false` to disable this module.

It may looks like
```
...
  "modules": {
    "better_fake_player": {
      "enable": false,
    },
...
```

Then you save the edit.

**The second method**: you can just simple backup your `config/fuji` folder, and move it to another way, let fuji generate the default configurations, and you can see the difference between the newer and older configuration file structure.

**Comment by sakurawald** [comment]
> I've installed carpet mod and ran fuji without any other mods except for the dependencies but it still crashed with the same [logs](https://pastes.dev/BLk39JQDmQ)

You don't need to install `carpet` module. We only need to install `carpet` module if you enable `BetterFakePlayer module` or `BetterInfoModule`.
In your situation, you don't enable `BetterFakePlayer` module explicitly, but because the in the latest verison, fuji changes the configuration structure, causing the configuration key `module.better_fake_player.enable` missing. (If a key is missing, fuji will consider it to be enabled by default).

The way you should do is to fix the structure of configuration file `config.json`.

PS: currently, fuji still can't auto merge 2 different configuration structures if they differs too much. so it may occurs some configuration keys missing in some version updates. 
If this case happens, you can see the `error` message send by fuji, which is used to warn the user, that the configuration structure is in-compatible.

**Comment by sakurawald** [comment]
> I'm sorry but idk how to do this myself 🙏

Try this version, it should work.

https://modrinth.com/mod/fuji/version/L5X6ac7Z

**Comment by Tanjiraaaaa** [comment]
> > I'm sorry but idk how to do this myself 🙏
> 
> Try this version, it should work.
> 
> https://modrinth.com/mod/fuji/version/L5X6ac7Z

Yes, this works, thanks!
