### ISSUE TITLE
Is there any way to convert the placeholders to another type?

### ISSUE THREAD

**Issue by Itsporo** [fuji-fabric/fuji#38]
- For example: %fuji:item% I want to change to <item> to make it easier for players to chat.
- One more thing is that I currently want to edit the way these placeholders are displayed when chatting but I can't find it. I have adjusted Inventory and Ender Chest but Item is not found in lang folder.
- Hope you improve this issue, /fuji reload does not reload language edits. Sometimes I can reload but I don't understand why.

**Comment by sakurawald** [comment]
Q1: You can use the `rewrite` in `chat module`, which can rewrite the players's messages into another message, but you can't change the placeholder name, it's registered in code. 
The default chat rewrite is from `item` to `%fuji:item%`, which is an abbrv.

```
          {
            "regex": "(?<=^|\\s)item(?=\\s|$)",
            "replacement": "%fuji:item%"
          },
```

Q2: The item display name can't be changed from language file, since the item name is decided by the stack. Fuji will directly show the name of the item, since it's more clear, and convenient.

Q3: The language file hot reload is added sinve v1.3.5. In the old versions, the language file is lazy-loading, so sometimes it looks like it can hot reload, but it's not.

**Comment by Itsporo** [comment]
Q2: Is there any way to adjust the format?
- I have no problem displaying the item but now I want to edit it a bit like removing the square brackets and changing the color.

**Comment by sakurawald** [comment]
> Q2: Is there any way to adjust the format?
> 
> * I have no problem displaying the item but now I want to edit it a bit like removing the square brackets and changing the color.

See the v1.3.5 version, i just added the custom item display text feature into it.

**Comment by Itsporo** [comment]
> > Q2: Is there any way to adjust the format?
> > 
> > * I have no problem displaying the item but now I want to edit it a bit like removing the square brackets and changing the color.
> 
> See the v1.3.5 version, i just added the custom item display text feature into it.

Thanks
