### ISSUE TITLE
Is the world module the module that allows me to create multiple worlds and I can teleport between them?

### ISSUE THREAD

**Issue by Itsporo** [fuji-fabric/fuji#42]
- For example, if I want to use the rtp module, can I set it to teleport to another world when I turn on the world module?

**Comment by sakurawald** [comment]
Q1: The `world module` provides general purpose world management, you can create, delete and teleport to any dimension that exists in your server.

Currently, the command `/world tp` actually calls the `random teleport`, which is used by the `/rtp command`.

If you just want to teleport to a dimension without rtp, you can use `/execute in <dimension-name> run tp <player> ~ ~ ~`

Q2: the `rtp module` is per-dimension configurable, you can set extra configuration for the extra dimensions created by the `world module`. For a new created dimension, you need to add the dimension configuration into the rtp module's `dimension` list, so that you can rtp in the dimension.

The `/world tp` command and `/rtp` command now share the same teleport codes, but you can use these 2 modules separately.

Q3: currently, the `/rtp` not support to specify a dimension, but the feature will added in recent future.

**Comment by Itsporo** [comment]
> Q1: The `world module` provides general purpose world management, you can create, delete and teleport to any dimension that exists in your server.
> 
> Currently, the command `/world tp` actually calls the `random teleport`, which is used by the `/rtp command`.
> 
> If you just want to teleport to a dimension without rtp, you can use `/execute in <dimension-name> run tp <player> ~ ~ ~`
> 
> Q2: the `rtp module` is per-dimension configurable, you can set extra configuration for the extra dimensions created by the `world module`. For a new created dimension, you need to add the dimension configuration into the rtp module's `dimension` list, so that you can rtp in the dimension.
> 
> The `/world tp` command and `/rtp` command now share the same teleport codes, but you can use these 2 modules separately.
> 
> Q3: currently, the `/rtp` not support to specify a dimension, but the feature will added in recent future.

- Ok, thank you!
