### ISSUE TITLE
Fuji's commands doesn't work on 1.21 version 1.3.5

### ISSUE THREAD

**Issue by Tanjiraaaaa** [fuji-fabric/fuji#45]
Here are the [logs](https://mclo.gs/e3BZAIW)
I can see the command suggestion in the chat when typing it out, but when executed, nothing happens.

**Comment by sakurawald** [comment]
It seems like there is something wrong in the `fuji/config.json`. (maybe check the `command_rewrite` module options)
See the logs in line 966, which indicates the missing configuration keys.

Can you provide the config.json file?

In `command_rewrite.regex` list, you should delete the `null` entry, since it's invalid entry, and cause the error.

**Comment by Tanjiraaaaa** [comment]
Alright I've fixed it, but I went and deleted the config file to reset the whole thing at first 🙏
