### ISSUE TITLE
[Feature Request]Customizable capes

### ISSUE THREAD

**Issue by yizexiaomu** [fuji-fabric/fuji#54]
On the basis of the skin module, we hope to customize cloaks. Players can choose all cloaks officially released by MC to match their skins (although this idea may be quite difficult to implement, as it is just an idea, we hope the author can consider it)

**Comment by sakurawald** [comment]
Custom capes will be interesting, this feature will be added in next update about `skin module`, if i get more time.

**Comment by sakurawald** [comment]
It seems it's impossible to customize the capes without the installation of client-side mods.

I would just recommend to use a custom cape loader in the client-side, and with 3rd-cape api.

**Comment by sakurawald** [comment]
I have check it again, it's still impossible.

The skin customization works, because there are lots of skin websites tracking a texture used by players, and some websites allow you to upload a custom skin image, because mojang allows the custom skin image.

However, for capes, there is only pre-defined capes by mojang, and a `texture` is composed by `skin` and `cape`, they are `signed` together. It's impossible to have a custom skin and custom cape as a combination, and also keeps a valid signature for client-side validation.
