### ISSUE TITLE
Excessive mod size leads to complex modules

### ISSUE THREAD

**Issue by yizexiaomu** [fuji-fabric/fuji#59]
Nowadays, the volume of fuji is getting larger and the number of modules is increasing. If all modules are placed on one module, it will become very difficult to configure. Can we cut modules of the same type into 3-4 mods

**Comment by sakurawald** [comment]
All the modules are organized in a tree-like structure, which is natural and easy understood. Modules are grouped by there features, not by the size of file, not by the literal numbers.
The tree structure is more advanced, and more expressive, if we flatten the tree-structure into the linear-structure, things will mess up. And there is also no point to break up things that share the same feature, which totally violates the group criterion.

It's recommend that the user should use a `modern text editor`, like `visual studio code`, like `vim` or `emacs`, which can highlight symbols and reveals the the clear structure of the file. (The official wiki provides many useful information about how to choose editor and auxiliary tools like some generators)

Since fuji is a pure server side mod, it also requires a little more understand and more skills to use, compared to the client-side mod which only focus on non-technical user.

**Comment by sakurawald** [comment]
This should be addressed in `fuji v1.5.9`, since this version, i have cut down the tree into small pieces. The big one file `config/fuji/config.json` is splited into `config/fuji/modules/<module-path>/config.json`.

Also, the file size of `fuji` is decreased from `9.02Mib` in `fuji v1.2.4` to `2.21 Mib` in `fuji v1.6.1`, i have replace many big libraries and implement the function in a vanilla way.
