### ISSUE TITLE
Zh_CN text error and fix

### ISSUE THREAD

**Issue by 7starsseeker** [fuji-fabric/fuji#85]
there are some garbled characters in zh_cn text. here is fixed file.
[zh_cn.json](https://github.com/user-attachments/files/17016364/zh_cn.json)

**Comment by sakurawald** [comment]
Hello, can you point out which language keys the garbled characters are in?
Also, can you check if the problem exists in the latest language file which locates in https://github.com/sakurawald/fuji/tree/dev/crowdin, because fuji will not override the language file once there is already a file exists.

I have check the language file, and it seems to be no problem, using UTF-8 encoding.

**Comment by 7starsseeker** [comment]
Sorry, it should be my problem.
I regenerated the relevant file and the corresponding text is fine. Before it should have been a generation problem with the old version. Sorry about that.
That one is indeed UTF-8 encoded.
